# High priority - These functions are generally considered insecure
high = ["strcpy", "sprintf", "test"]

# Medium priority - These functions are interesting and should be checked for insecure use cases
medium = []

# Low priority - Code paths involving these functions should be carefully checked
low = []
