name: build

permissions:
  contents: read

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: sccache
        uses: mozilla-actions/sccache-action@v0.0.8
      - name: rustfmt
        run: cargo fmt --all --check
      - name: clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: build
        run: cargo build

  build-macos:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: sccache
        uses: mozilla-actions/sccache-action@v0.0.8
      - name: build
        run: cargo build

  build-windows:
    runs-on: windows-latest
    steps:
      - name: install clang/llvm
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "20"
          directory: "${{ runner.temp }}/llvm-20"
      - name: configure clang/llvm environment
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: sccache
        uses: mozilla-actions/sccache-action@v0.0.8
      - name: build
        run: cargo build
